name: Daily Auto-Commit

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp file
        run: |
          echo "Last update: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > timestamp.txt

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add timestamp.txt
          git commit -m "Auto-update: $(date -u '+%Y-%m-%d')" || echo "No changes to commit"
          git push
